### ISSUE TITLE
Robots.txt DirectoryNotFoundException

### ISSUE THREAD

**Issue by leventefabry-mof** [patrickdemooij9/SeoToolkit.Umbraco#111]
Hi, I tried to add the following package (SeoToolkit.Umbraco.RobotsTxt v2.1.0) to my Umbraco (version 10.1.0) and after the build, I got the following error:

DirectoryNotFoundException: C:\Users\leven\.nuget\packages\seotoolkit.umbraco.common\2.1.0\staticwebassets\
Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(string root, ExclusionFilters filters)
Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(string root)
Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader+<>c.<UseStaticWebAssetsCore>b__1_0(string contentRoot)
Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func<string, IFileProvider> fileProviderFactory)
Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
Microsoft.AspNetCore.WebHost+<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
Microsoft.AspNetCore.Hosting.GenericWebHostBuilder+<>c__DisplayClass9_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder)
Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
Microsoft.Extensions.Hosting.HostBuilder.Build()
Umbraco.Cms.Web.Common.Hosting.UmbracoHostBuilderDecorator.Build()
Wilderness.Web.Program.Main(string[] args) in Program.cs
+
        => CreateHostBuilder(args)
        
Do you have any idea what I could do?
Thanks in advance!

**Comment by patrickdemooij9** [comment]
Hi @leventefabry-mof 

Are you perhaps running this in Local IIS? If so, did you add the correct permissions to the NuGet cache folder? https://our.umbraco.com/Documentation/Fundamentals/Setup/install/iis#add-permissions-to-nuget-cache-folder

If the permissions aren't setup correctly, it'll give a DirectoryNotFoundException. It could also be caused by something else, but this would be a good first step

**Comment by leventefabry-mof** [comment]
Hello @patrickdemooij9,
I'm sorry you're right that was the problem :D 
But after the installation, I got another problem if I click on the SEO Toolkit menu:

Received an error from the server
An error occurred
Object reference not set to an instance of an object.

Exception Details
System.NullReferenceException, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Object reference not set to an instance of an object.

Thanks in advance!

**Comment by patrickdemooij9** [comment]
@leventefabry-mof 
Good to hear that we've fixed the first issue.
I am not quite sure about the second one. I'll see if I can reproduce it later today and hopefully have a fix ready after that. I'll keep you updated!

**Comment by patrickdemooij9** [comment]
Good news! I have been able to reproduce the issue. The issue happens when you only have a single package installed with a tree node. Not quite sure why, but it is something within the code of Umbraco.

Currently trying to figure out how to work around that issue, so I might not have the fix ready today. If you really want to get around the issue, then installing another package with a tree node (redirects, script manager) will fix it for the time being.

**Comment by patrickdemooij9** [comment]
Hi @leventefabry-mof 
Your issue should now be fixed in the latest RobotsTxt version (2.1.1)

**Comment by leventefabry-mof** [comment]
Hi @patrickdemooij9 ,
Thanks for the quick help!
