### ISSUE TITLE
Load balanced support for Script Manager?

### ISSUE THREAD

**Issue by ianleeder** [patrickdemooij9/SeoToolkit.Umbraco#218]
Hi Patrick,

I don't have a lot of info to go on at this point, but I wanted to get the question out there.  Do you know if SEOToolkit supports load balanced configuration?

I ask because I'm having trouble with Script Manager.  I have one backoffice server, two frontend.  If I create a new entry in the backoffice, it doesn't show on the frontend servers (either rendered, or in the forbidden backoffice).

Do you know when the script manager settings are loaded/read/consumed?  Do I need to also do a publish from the backoffice?
For now I restarted the frontend servers, and they took up the setting correctly.

**Comment by patrickdemooij9** [comment]
Hi @ianleeder 

SeoToolkit does not support load balancing as of the current versions. In this PR(https://github.com/patrickdemooij9/SeoToolkit.Umbraco/pull/222), I added cache refreshers so that cache is correctly cleared on all servers, so this should help with your Script Manager issues. This will be released in the next update (today or tomorrow).

**Comment by ianleeder** [comment]
Thanks @patrickdemooij9!
Will this go into Umbraco10 also?

**Comment by patrickdemooij9** [comment]
Hi @ianleeder 
Yes, this has also been cherry picked into the Umbraco 10 version: https://github.com/patrickdemooij9/SeoToolkit.Umbraco/releases/tag/3.3.0
